import random
div002_student_names = [
    'Mukhammadov Muminjon Otajon Ugli',
    'Kutlimuratov Madrakhim Khushnud Ugli',
    'Akimov Sarvar Ravshan Ugli',
    'Akhmadjonov Samandar Anvarjon Ugli',
    'Shokirov Saidalo Nematillo Ugli',
    'Sharifov Azizbek Sharofovich',
    'Khudaynazarov Sunnatbek Bakhodir Ugli',
    'Carrasco Soriano Diana Laura',
    'Zokirov Diyorbek Botir Ugli',
    'Muhammadkhonov Mavlonkhon Muhriddinkho',
    'Vu Nguyen Bao Ngoc',
    'Murtozaev Sardor Muzaffar Ugli',
    'Rustamov Shamsiddin Azam Ugli',
    'Kakharova Sevinch Javlon Kizi',
    'Jabborov Sunnatjon Bakhtiyor Ugli',
    'Hamidkhonov Amirkhon Obidkhon Ugli',
    'Mustafakulov Azizbek Furkat Ugli',
    'Ziyaviddinov Ibrohim Ilhom Ugli',
    'Turaev Jahongir Bakhtiyorovich',
    'Ishonkulov Jakhongir Khusan Ugli',
    'Chinieva Shokhida Dilshodovna',
    'Khamdamov Kamronbek Laziz Ugli',
    'Tursunov Firdavs Farhodovich',
    'Ha Thi My Linh',
    'Kurbonova Nilufar Mizrobovna',
    'Orziev Diyorbek Matnazar Ugli',
    'Obidov Dilshod Khurshedovich',
    'Togaev Ravshan Khayritdin Ugli',
    'Shodmonov Rustam Bakhtiyor Ugli',
    'Khudoyberdiev Madaminbek Pulat Ugli',
    'Ilhomov Mansur Ilhom Ugli',
    'Kakhorjonov Mansurbek Tokhirjon Ugli',
    'Tsogoo Munkhzul',
    'Adhamov Muhammadaziz Gayratjon Ugli',
    'Koilybay Miras',
    'Muhammedov Mironshoh Mirkhon Ugli',
    'Abdurasulov Mirsaid Alimardonovich',
    'Nematjonov Bahodir Nurmukhamad Ugli',
    'Pak Georgiy',
    'Abduvokhidov Bekmurod Abdulkhodi Ugli',
    'Eshmirzaev Sarvar Raufjonovich',
    'Kosimov Shamskamar Jahongir Ugli',
    'Baratov Sokhibjon Khurshedovich',
    'Shokulov Shohruh Tuymurod Ugli',
    'Meliboev Shukurullo Fakhriddin Ugli',
    'Baktybek Uulu Arsen',
    'Shermirzaev Abbosbek Isroiljon Ugli',
    'Kiyomov Asadbek Kosimjon Ugli',
    'Mukhtorjonov Asilbek Murodjon Ugli',
    'Suiindik Akniyet',
    'Nabijonov Javokhir Pulatjon Ugli',
    'Nimatilaev Javokhir Izatillo Ugli',
    'Khursanaliev Javokhir Mukhiddin Ugli',
    'Abdulkhodiev Jobirkhon Rus Tamjon Ugli',
    'Malabon Julliane Samantha',
    'Chaw Thiri San',
    'Sobitkhonov Kudratkhon Odilkhon Ugli',
    'Bekzhanov Tariel Bekzhanovich',
    'Raykhonov Tilov Alisher Ugli',
    'Otamirzaev Fayozbek Farkhodjon Ugli',
    'Pirmatov Feruzbek Ermat Ugli',
    'Davlatov Hamidullo Nosirjon Ugli'
 ]

div001_student_names=[
    'Sirojiddinov Abdulaziz Ulugbek Ugli',
    'Abdukarimov Humoyunbek Olimjon Ugli',
    'Ochilov Shokhrukh Uchkun Ugli',
    'Abdurasulov Farrukhbek Ziyovuddin Ugli',
    'Chutboev Habibullo Islombek Ugli',
    'Ravshanbekov Khikmatullo Khayotbek Ugl',
    'Matyakubov Azizbek Yorkinbek Ugli',
    'Ilkhomov Akhrorbek Mardonbek Ugli',
    'Shabonov Abdullo Abbos Ugli',
    'Rasulov Elyor Dusyor Ugli',
    'Yuldoshev Javokhir Yusufjon Ugli',
    'Ghising Gyalchhen',
    'Khursanov Nazarbek Ulugbek Ugli',
    'Tologonova Datkaiym Temirbekovna',
    'Bayasgalan Delgerjargal',
    'Akhmadova Durdona Odiljon Kizi',
    'Olimjonov Diyorjon Sohibjon Ugli',
    'Akhmadova Dilnavoz Odiljon Kizi',
    'Bakhromov Rustam Nozim Ugli',
    'Egamkulova Makhliyo Abduraim Kizi',
    'Orifova Mokhinur Khakim Kizi',
    'Yusupov Murodilla Nizomiddin Ugli',
    'Avazkhonov Murtazokhon Yusufkhon Ugli',
    'Nosirkhonova Mubina Fakhriddin Kizi',
    'Umarova Mukaddaskhon Khursandjon Kizi',
    'Kodirov Muhammadkodir Shokir Ugli',
    'Shavkatov Mukhammadazam Shukhratbek Ug',
    'Tuychiev Mirjalol Kushmatjon Ugli',
    'Karimov Bekhruzbek Gafurjon Ugli',
    'Sultonov Begzod Azamat Ugli',
    'Khatamjonov Bekzodjon Bunyodjon Ugli',
    'Hamraev Sardor Khikmatovich',
    'Urdushev Sarvar Ulugbek Ugli',
    'Usmanov Sarvarbek Dilshod Ugli',
    'Hoshimov Shahriyor Ahmadjon Ugli',
    'Normamatova Shakhrizoda Gulomjon Kizi',
    'Ibodullaeva Shakhzoda Khamidjon Kizi',
    'Ozodov Sherzod Khamdam Ugli',
    'Norboeva Sevinch Akmal Kizi',
    'Yakhshimurodova Sevinchbonu Khudarga K',
    'Shomurodov Shohruh Olimjon Ugli',
    'Khaitov Shokhrukhjon Shukhrat Ugli',
    'Tadzhieva Amira',
    'Esanboev Abrorjon Akramjon Ugli',
    'Fayzullaev Asadbek Khayrullo Ugli',
    'Abduldaeva Aiana Ulanbekovna',
    'Saydullaeva Aziza Olimovna',
    'Akramov Akromjon Ikrom Ugli',
    'Abdulkhaev Akbarjon Akhmad Ugli',
    'Subkhiddinov Anvarbek Kambarjon Ugli',
    'Dushamboev Ogabek Nurmat Ugli',
    'Rayimkulov Otabek Ilkhomjon Ugli',
    'Vahobova Ugiloy Bakhtiyor Kizi',
    'Ergashev Ilhomjon Odiljon Ugli',
    'Pirimova Zarnigor Akhadovna',
    'Igamberdiev Javokhir Eldor Ugli',
    'Bakhronova Jasmina Orzumurodovna',
    'Khonimkulov Jaloliddin Ismatilla Ugli',
    'Uralova Zebo Bahodirjon Kizi',
    'Nakhalboev Juratbek Bakhodir Ugli',
    'Abdumukhiddinov Ziyodbek Ikboljon Ugli',
    'Bulturboev Fakhriddin Farkhod Ugli',
    'Pivavar Darya',
    'Siddikov Khusniddin Bekhzod Ugli'
 ]

selected_student = random.choice(div002_student_names)
print(selected_student)